home: /data/jenkins
main_job_src: service-workflow-config.xml
service_redeploy_src: service-redeploy-config.xml

configs: [
  { src: "dev-config.xml", dir: "/data/jenkins/nodes/dev", file: "config.xml", mode: "0777" },
  { src: "rpi-config.xml", dir: "/data/jenkins/nodes/rpi", file: "config.xml", mode: "0777" },
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml", mode: "0777" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
    name: "books-ms",
    service_name: "books-ms",
    src: "{{ main_job_src }}"
  }, {
    name: "books-ms-multibranch",
    service_name: "books-ms",
    src: "service-workflow-multibranch-config.xml"
  }, {
    name: "books-ms-blue-green",
    service_name: "books-ms",
    src: "service-blue-green-config.xml"
  }
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - workflow-scm-step
  - docker-workflow
  - template-project
